export const API_MODEL_REPOSITORY = Symbol("API_MODEL_REPOSITORY");

export const AI_COMMINICATE_API = Symbol("AI_COMMINICATE_API");

export const AI_COMMINICATE_REPOSITORY = Symbol("AI_COMMINICATE_REPOSITORY");
